export {default as banner1 } from "@assets/images/main-banner1.webp"
export {default as banner2 } from "@assets/images/main-banner2.webp"
export {default as sbanner1} from "@assets/images/small-banner1.webp"
export {default as sbanner2} from "@assets/images/small-banner2.webp"
export {default as sbanner3} from "@assets/images/small-banner3.webp"
export {default as sbanner4} from "@assets/images/small-banner4.webp"
export {default as gift }    from "@assets/images/gift.png"
export {default as discount} from "@assets/images/discont.png"
export {default as service1} from "@assets/images/service1.png"
export {default as service2} from "@assets/images/service2.png"
export {default as service3} from "@assets/images/service3.png"
export {default as service4} from "@assets/images/service4.png"
export {default as service5} from "@assets/images/service5.png"
export {default as service6} from "@assets/images/service6.png"
export {default as service7} from "@assets/images/service7.png"
export {default as service8} from "@assets/images/service8.png"
export {default as service9} from "@assets/images/service9.png"
export {default as service10} from "@assets/images/service10.png"
export {default as brand1} from "@assets/images/brand-1.png"
export {default as brand2} from "@assets/images/brand-2.png"
export {default as brand3} from "@assets/images/brand-3.png"
export {default as brand4} from "@assets/images/brand-4.png"
export {default as brand5} from "@assets/images/brand-5.png"
export {default as brand6} from "@assets/images/brand-6.png"
export {default as brand7} from "@assets/images/brand-7.png"
export {default as brand8} from "@assets/images/brand-8.png"
export {default as brand9} from "@assets/images/brand-9.png"
export {default as brand10} from "@assets/images/brand-10.png"
export {default as brand11} from "@assets/images/brand-11.png"
export {default as brand12} from "@assets/images/brand-12.png"
export {default as Error404} from "@assets/images/404.webp"

export {default as zephyrus} from "@assets/images/imgBlog/zephyrus-g14-2024.webp"
export {default as samsungWatch} from "@assets/images/imgBlog/samsung-galaxy-watch-ultra.webp"
export {default as surfacePro9} from "@assets/images/imgBlog/microsoft-surface-pro-9-desktop.webp"
export {default as lgWashingMachine} from "@assets/images/imgBlog/lg-washing-machine-best.webp"
export {default as smartphones} from "@assets/images/imgBlog/best-smartphones-buying-guide.webp"

export {default as speaker} from "@assets/images/imgBlog/speaker.webp"
export {default as digitalCamra} from "@assets/images/imgBlog/sony Alpha A6400.webp"
export {default as redmi13} from "@assets/images/imgBlog/Redmi 13 xiaomi.webp"
export {default as motorola} from "@assets/images/imgBlog/Pulse Motorola.webp"
export {default as miXiaomi} from "@assets/images/imgBlog/Mi Band 8 xiaomi.webp"
export {default as ipad} from "@assets/images/imgBlog/iPad (9th Generation).webp"

export {default as speakerB} from "@assets/images/imgBlog/speakerB.webp"
export {default as digitalCamraB} from "@assets/images/imgBlog/sony Alpha A6400B.webp"
export {default as redmi13B} from "@assets/images/imgBlog/Redmi 13 xiaomiB.webp"
export {default as motorolaB} from "@assets/images/imgBlog/Pulse MotorolaB.webp"
export {default as miXiaomiB} from "@assets/images/imgBlog/Mi Band 8 xiaomiB.webp"
export {default as ipadB} from "@assets/images/imgBlog/iPad (9th Generation)B.webp"

export {default as SPORT} from "@assets/images/imgBlog/sport.webp"
export {default as AirPodsPro} from "@assets/images/imgBlog/Air.webp"
export {default as Opo} from "@assets/images/imgBlog/opo.webp"
export {default as s24} from "@assets/images/imgBlog/s24.webp"
export {default as hp} from "@assets/images/imgBlog/Hp.webp"
export {default as tcl} from "@assets/images/imgBlog/tcl.jpg"

export {default as SPORTB} from "@assets/images/imgBlog/sport2.webp"
export {default as AirPodsPro2} from "@assets/images/imgBlog/Air2.webp"
export {default as OpoB} from "@assets/images/imgBlog/opo2.webp"
export {default as s24B} from "@assets/images/imgBlog/s24B.webp"
export {default as hpB} from "@assets/images/imgBlog/HpB.webp"
export {default as tclB} from "@assets/images/imgBlog/tclB.webp"

export {default as AppleWatch} from "@assets/images/imgBlog/Apple-series-9-aluminum.png"
export {default as LaptopAsus} from "@assets/images/imgBlog/Vivobook 15.webp"
export {default as XiaomiHedest} from "@assets/images/imgBlog/NIB REDMI BUDS.webp"
export {default as Iphone13} from "@assets/images/imgBlog/iphon13ch.webp"

export {default as fourLine} from "@assets/images/4line-vertical.jpg"
export {default as threeLine} from "@assets/images/3line-horizental.jpg"
export {default as twoLine} from "@assets/images/2line-vertical.jpg"
export {default as threeLineV} from "@assets/images/3Line.jpg"